### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by yi1z** [karansher/computer-graphics-bounding-volume-hierarchy#26]
Ok so this is a general question... How many of us are struggling with getting cmake to use? I tried directly downloading eigen and libigl packages through vcpkg and change the include path; I also copied the eigen folder from a3 to a4, but none of them seem to be able to get cmake realize that eigen (at least Eigen/Core) exists xd. If anyone has a solution please educate us

**Comment by yi1z** [comment]
Guys I probably figured out a solution. So I'm not sure exactly how it works, but what I did was to download vcpkg from https://vcpkg.io/en/index.html, and then use vcpkg to install eigen and libigl. Then redownload a4 starter file and build should solve the problem.

**Comment by ValentinaManferrari** [comment]
Hey! I still have the problem I went to the office hours yesterday and waiting to hear back from the professor. 
I am trying to use the package you recommended but it seems I am unable to download the required packages with vcpkg... will keep trying

**Comment by philip-huang** [comment]
A few possible suggestions:
are you cloning the libigl submodule? If you forgot to recursive clone, try ```git submodule update --init```
if you did clone and see weird compiler errors, in the release mode, you need to add ```#include <Eigen/Geometry>``` to the file with the error.

**Comment by yi1z** [comment]
https://github.com/opencv/opencv/issues/14868
Maybe check this this link, it was about the same problem but on Linux, but it contains many potential solutions

**Comment by yi1z** [comment]
> A few possible suggestions: are you cloning the libigl submodule? If you forgot to recursive clone, try `git submodule update --init` if you did clone and see weird compiler errors, in the release mode, you need to add `#include <Eigen/Geometry>` to the file with the error.

Also I'm pretty sure I cloned everything needed since I copied the given cmd to start, but it didn't work as it keeps saying that line 179 of libigl\DownloadProject.cmake is wrong, which suggests it cannot download eigen package? Anyway I got things solved after installing eigen by myself so there might be a slight problem with function(download project) in DownloadProject.cmake
The cmd used to clone
![image](https://user-images.githubusercontent.com/90294263/197822235-5011ea30-bc6d-4535-b6a2-661cafb89198.png)

The line which reports the problem
![image](https://user-images.githubusercontent.com/90294263/197823353-5a2e0087-d06c-4356-b36b-5daaf3a06bf4.png)

The function which might be the cause of the problem
![image](https://user-images.githubusercontent.com/90294263/197823423-c5a5880e-6f70-4482-b670-521607c3ae44.png)
